### PR TITLE
Fix destructuring assignment errors

### LINKED ISSUE #406: ClassCastException when compiling malformed destructuring expression
Input to Rhino 1.7.8:
```
(1 ? ({x: (y)}) : (490)) = 1
```
Expected: ReferenceError (Invalid left-hand side in assignment)
Instead, I get:
```
java.lang.ClassCastException: org.mozilla.javascript.Node cannot be cast to org.mozilla.javascript.ast.ObjectLiteral

	at org.mozilla.javascript.Parser.destructuringAssignmentHelper(Parser.java:3932)
	at org.mozilla.javascript.Parser.createDestructuringAssignment(Parser.java:3902)
	at org.mozilla.javascript.IRFactory.createAssignment(IRFactory.java:2235)
	at org.mozilla.javascript.IRFactory.transformAssignment(IRFactory.java:432)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:212)
	at org.mozilla.javascript.IRFactory.transformExprStmt(IRFactory.java:516)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:209)
	at org.mozilla.javascript.IRFactory.transformScript(IRFactory.java:1042)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:192)
	at org.mozilla.javascript.IRFactory.transformTree(IRFactory.java:117)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2540)
	at org.mozilla.javascript.Context.compileString(Context.java:1507)
	at org.mozilla.javascript.Context.compileString(Context.java:1496)
```

Found using [JQF](https://github.com/rohanpadhye/jqf).

### LINKED ISSUE #1187: Error with destructuring array assignment(?)
The following cannot be evaluated and leads to an exception with 1.7R3 and later
var a = [1, 2]; var b = 0; [a[b+1], a[b]] = [a[b], a[b+1]]; a[0]

Exception:
```
java.lang.IllegalStateException: FAILED ASSERTION: unexpected token: ADD
	at org.mozilla.javascript.Kit.codeBug(Kit.java:366)
	at org.mozilla.javascript.IRFactory.decompile(IRFactory.java:2498)
	at org.mozilla.javascript.IRFactory.decompileElementGet(IRFactory.java:2549)
	at org.mozilla.javascript.IRFactory.decompile(IRFactory.java:2492)
	at org.mozilla.javascript.IRFactory.decompileArrayLiteral(IRFactory.java:2509)
	at org.mozilla.javascript.IRFactory.decompile(IRFactory.java:2469)
	at org.mozilla.javascript.IRFactory.transformAssignment(IRFactory.java:441)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:222)
	at org.mozilla.javascript.IRFactory.transformExprStmt(IRFactory.java:559)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:219)
	at org.mozilla.javascript.IRFactory.transformScript(IRFactory.java:1133)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:201)
	at org.mozilla.javascript.IRFactory.transformTree(IRFactory.java:121)
	at org.mozilla.javascript.Context.parse(Context.java:2484)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
	at org.mozilla.javascript.Context.compileString(Context.java:1369)
	at org.mozilla.javascript.Context.compileString(Context.java:1357)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
	at de.ndn.labs.RhinoBugTest.main(RhinoBugTest.java:16)
```

But it is evaluated with 1.7R2 (to "2"). I really don't understand why this works in a very old version and fails in all newer versions.

The only thing that works is removing the "+" in the array access:
var a = [1, 2]; var b = 0; var c = 1; [a[c], a[b]] = [a[b], a[c]]; a[0]

Minimal Java example here (and attached)
https://github.com/ndeuma/rhino-bugtest

[rhino-bugtest.zip](https://github.com/mozilla/rhino/files/8119083/rhino-bugtest.zip)

### PR DESCRIPTION
**Pull request by tuchida**
### Closes #1187
```
js> var a = []; var b = 0; [a[b+1]] = [123];
Exception in thread "main" java.lang.NullPointerException
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(BodyCodegen.java:967)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(BodyCodegen.java:1233)
	at org.mozilla.javascript.optimizer.BodyCodegen.visitSetElem(BodyCodegen.java:4143)
```
This error has been corrected in [this commit](https://github.com/mozilla/rhino/pull/1529/commits/1fd026f0207ac54ac7c40bdcdd60c6501f16589b).

### Closes #406
```
js> (1 ? {} : 490) = 1
Exception in thread "main" java.lang.ClassCastException: class org.mozilla.javascript.Node cannot be cast to class org.mozilla.javascript.ast.ObjectLiteral (org.mozilla.javascript.Node and org.mozilla.javascript.ast.ObjectLiteral are in unnamed module of loader 'app')
	at org.mozilla.javascript.Parser.destructuringAssignmentHelper(Parser.java:4046)
	at org.mozilla.javascript.Parser.createDestructuringAssignment(Parser.java:4016)
	at org.mozilla.javascript.IRFactory.createAssignment(IRFactory.java:2056)

```
This error has been corrected in [this commit](https://github.com/mozilla/rhino/pull/1529/commits/5f55f04fe4082bcb5e8f35a47b910562574491e8).

### CODE REVIEW

File: rhino/src/main/java/org/mozilla/javascript/IRFactory.java [hunk 1]
```diff
@@ -1476,7 +1476,9 @@ private Node createForIn(
             Node newBody = new Node(Token.BLOCK);
             Node assign;
             if (destructuring != -1) {
-                assign = parser.createDestructuringAssignment(declType, lvalue, id);
```
Comment (tuchida) [inline rhino/src/main/java/org/mozilla/javascript/IRFactory.java:1479]:
```js
var a;
for ([a] of [[1], [2], [3]]) {
  //
}
```

File: rhino/src/main/java/org/mozilla/javascript/IRFactory.java [hunk 2]
```diff
@@ -2053,7 +2055,8 @@ private Node createAssignment(int assignType, Node left, Node right) {
                     parser.reportError("msg.bad.destruct.op");
                     return right;
                 }
-                return parser.createDestructuringAssignment(-1, left, right);
+                return parser.createDestructuringAssignment(
```
Comment (tuchida) [inline rhino/src/main/java/org/mozilla/javascript/IRFactory.java:2058]:
```js
var a;
[a] = [1];
```

**Review by tuchida — COMMENTED** [review]
https://github.com/mozilla/rhino/blob/5f55f04fe4082bcb5e8f35a47b910562574491e8/rhino/src/main/java/org/mozilla/javascript/IRFactory.java#L1112
Because a variable declaration cannot be an expression, no `transform` is passed here.
```js
var [a.b] = []; // SyntaxError
```

File: tests/testsrc/test262.properties [hunk 3]
```diff
@@ -3186,6 +3186,206 @@ language/expressions/arrow-function 209/333 (62.76%)
     scope-paramsbody-var-close.js
     scope-paramsbody-var-open.js
 
+language/expressions/assignment 200/468 (42.74%)
```
Comment (gbrail) [inline tests/testsrc/test262.properties:3189]: I'm trying to refresh my memory on test262.properties -- is this a long list of tests that we now have to disable becuase we broke them, or were these tests never run and we're actually able to pass 58% of them?

In other words, do these test262 changes represent an improvement, or a regression?

Comment (p-bakker) [reply tests/testsrc/test262.properties:3189]: The test262Suite only looks at tests in directories that are already included in trst262.properties

So what you're seeing here in inclusion of a new directory full of tests, some of which already pass

Ran into this recently, tried to create a PR that will include ALL directories automatically, because this is a gap in our 'security net'. Didn't get around to finish it though....

Comment (tuchida) [reply tests/testsrc/test262.properties:3189]: f772166a921a842a7ce86429f39b37319959be1c First I added `language/expressions/assignment` tests to test262.properties in the first commit.
1fd026f0207ac54ac7c40bdcdd60c6501f16589b And two of those tests were improved.

Comment (tuchida) [reply tests/testsrc/test262.properties:3189]: I added all directories to test262.properties. ref. #1531
I would like to merge that PR first.

**Comment by gbrail** [comment]
This looks good, but I merged your other 262.properties change and I'd feel better if you looked it over and resolved before merging. Thanks!

**Comment by tuchida** [comment]
> f772166a921a842a7ce86429f39b37319959be1c Add assignment tests of test262

Deleted the commit. No other changes have been made.
