### PR TITLE
Fix syntax error for comments in array

### LINKED ISSUE #602: Syntax error with comments in array declaration
The following javascript generates a syntax error when recording comments is enabled: var array = [/* */];

It can be solved by removing the "break" at the end of the "if (compilerEnv.isRecordingComments())" block in the method peekToken() in Parser.java .

### PR DESCRIPTION
**Pull request by PalAditya**
Fixes #602 

The error came from the fact that token type comment was not expected within array literal, so added that case to handle that error. Also added multiple test cases in ```testsrc/org/mozilla/javascript/tests/ParserTest.java``` under the function ```testCommentInArray()``` to check all possible cases (single/multiple/no comments, and comments between literals)

Please mention if something else needs to be fixed for this PR 😄

### CODE REVIEW

**Comment by PalAditya** [comment]
Capture
Just adding the local Jacoco coverage for easy reference :)

File: src/org/mozilla/javascript/Parser.java [hunk 1]
```diff
@@ -3272,7 +3272,10 @@ private AstNode arrayLiteral()
                     elements.add(new EmptyExpression(ts.tokenBeg, 1));
                     skipCount++;
                 }
-            } else if (tt == Token.RB) {
+            }else if(tt == Token.COMMENT) {
```
Comment (gbrail) [inline src/org/mozilla/javascript/Parser.java]: If I'm going to suggest only one thing, I'd prefer if changes kept the same coding style (spaces, newlines, etc) as the code around it. Unfortunately applying any one particular style to this ancient codebase is a big job, but if we can at least keep things consistent with the lines around them then we'll all be happier I think.

File: src/org/mozilla/javascript/Parser.java [hunk 2]
```diff
@@ -3272,7 +3272,10 @@ private AstNode arrayLiteral()
...
+                consumeToken();
+            }
+            else if (tt == Token.RB) {
```
Comment (gbrail) [inline src/org/mozilla/javascript/Parser.java]: Same here -- It looks like other code in this file puts "else" on the same line as the preceding brace, with a space between the brace and else...

Comment (PalAditya) [reply src/org/mozilla/javascript/Parser.java]: Noted. Will fix the formatting and push the changes.

**Comment by gbrail** [comment]
Thanks! I'm going to squash these two commits into one and merge them.
