### PR TITLE
fix for stringify array replacer mozilla/rhino#725

### LINKED ISSUE #725: An issue about JSON.stringify
##### Version

rhino-1.7.12

##### Test case

```js
var NISLFuzzingFunc=function(nislMutationParameter1){
    var a={"0":1, "1":2, "2":3, "name":4};
    var b=JSON.stringify(a, nislMutationParameter1); 
    print(b);
}; 
var nislMutationArgument1=["0", "1", "name", "name"]; 
NISLFuzzingFunc(nislMutationArgument1);
```

##### Execution steps

` java -jar rhino/rhino-1.7.12.jar -debug -version 200 testcase.js`

##### Output

```
 {"name":4,"name":4}
```

##### Expected behavior

```
{"0":1,"1":2,"name":4}
```

##### Description

The `JSON.stringify(value[, replacer[, space]])` method converts a JavaScript object or value to a JSON string, optionally including only the specified properties if a replacer array is specified, and the ES standard specifies that the output attributes should not contain duplicate attributes. When executing this test case, rhino has two problems: the first is that the attribute named by numeric characters cannot be output, and the second is to repeatedly output the same attribute.

contributor：  [@Wen Yi](https://github.com/YiWen-y)

### PR DESCRIPTION
**Pull request by tonygermano**
- Per spec, Numbers in an array replacer should be converted to strings
  prior to adding to the property list
- Duplicates should be removed during construction of the property list
- Changed some variables declared as List  to Collection instead because
  that is sufficient for how they are being used
- Moved LinkedList to array conversion from happening in every iteration of
  the jo method to happening once in the stringify method
- Convert strings items representing integers to their Integer value for
  correct property lookup

fixes #725

### CODE REVIEW

**Comment by tonygermano** [comment]
Relevant tests which both pass are:
- https://github.com/tc39/test262/blob/70bc32edab22b44db9d671ce505db8842ae200b6/test/built-ins/JSON/stringify/replacer-array-duplicates.js
- https://github.com/tc39/test262/blob/70bc32edab22b44db9d671ce505db8842ae200b6/test/built-ins/JSON/stringify/replacer-array-number.js

Tests are not yet run automatically, but are part of the effort in #817

File: src/org/mozilla/javascript/NativeJSON.java [hunk 1]
```diff
@@ -374,12 +388,12 @@ private static String jo(Scriptable value, StringifyState state) {
         state.indent = state.indent + state.gap;
         Object[] k = null;
         if (state.propertyList != null) {
-            k = state.propertyList.toArray();
```
Comment (tonygermano) [inline src/org/mozilla/javascript/NativeJSON.java:377]: `propertyList.toArray()` is called for every object and child object being stringified where propertyList is a LinkedList.

**Review by gbrail — COMMENTED** [review]
This seems fine to me, but I'd like to see that some tests are included. Does it make sense to wait and merge this after we get more tests from test262 working, or are there some other tests that you can add?

**Comment by tonygermano** [comment]
I can add a test using the examples from the linked issue. I didn't know if I needed to since it's going to be covered by test262, hopefully in the near-ish future.

**Comment by rbri** [comment]
I plan to go forward with test262 updates in small steps on a weekly basis

**Comment by tonygermano** [comment]
@gbrail I added some tests. The first time CircleCI tried to build, it failed with:
```
java.lang.AssertionError: In "testsrc/tests/js1_5/Regress/regress-211590.js":
 FAILED! Math.random should be random : Expected value 'between 48% and 52%', Actual value ' is 52.060' 
 ```
 
I reran the CircleCI build without changing any code, and it passed the second time. I'm guessing it was just a fluke with the rng.

**Comment by gbrail** [comment]
Works for me. Thanks!
