### PR TITLE
Try setting superblock locals from an initialised exception handler

### LINKED ISSUE #915: java.lang.VerifyError in language/statements/try of test262
When I enable language/statements/try in test262, I get the following error.

```
org.mozilla.javascript.tests.Test262SuiteTest > test262Case[js=language/statements/try/S12.14_A7_T1.js, opt=0, strict=false] FAILED
    java.lang.VerifyError at Test262SuiteTest.java:217

...

org.mozilla.javascript.tests.Test262SuiteTest > test262Case[js=language/statements/try/S12.14_A7_T3.js, opt=0, strict=false] FAILED
    java.lang.VerifyError at Test262SuiteTest.java:217
```
With JavaScript code like this
```js
try{
  try{
    throw "ex1";
  }finally{
    try{
      throw "ex2";
    }catch(er1){
    }
  }
}catch(er2){
}
```
I got an error like the following
```
Exception in thread "main" java.lang.VerifyError: Stack map does not match the one at exception handler 91
Exception Details:
  Location:
    org/mozilla/javascript/gen/_stdin__1._c_script_0(Lorg/mozilla/javascript/gen/_stdin__1;Lorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;Lorg/mozilla/javascript/Scriptable;[Ljava/lang/Object;)Ljava/lang/Object; @91: nop
  Reason:
    Type top (current frame, locals[5]) is not assignable to 'java/lang/Object' (stack map, locals[5])
  Current Frame:
    bci: @52
    flags: { }
    locals: { 'org/mozilla/javascript/gen/_stdin__1', 'org/mozilla/javascript/Context', 'org/mozilla/javascript/Scriptable', 'org/mozilla/javascript/Scriptable', '[Ljava/lang/Object;' }
    stack: { 'org/mozilla/javascript/JavaScriptException' }
  Stackmap Frame:
    bci: @91
    flags: { }
    locals: { 'org/mozilla/javascript/gen/_stdin__1', 'org/mozilla/javascript/Context', 'org/mozilla/javascript/Scriptable', 'org/mozilla/javascript/Scriptable', '[Ljava/lang/Object;', 'java/lang/Object', top, 'org/mozilla/javascript/Scriptable' }
    stack: { 'java/lang/Throwable' }
```
https://app.circleci.com/pipelines/github/mozilla/rhino/394/workflows/06f40ab3-873d-4ffd-b26f-753722081c8a/jobs/400/tests

I investigated the cause of this, but could not find it. If there is any way to find out, please let me know. For example, is there any way to isolate whether the StackMapTable is wrong or the bytecode itself is wrong?

### PR DESCRIPTION
**Pull request by carlosame**
The patch to `ClassFileWriter` contains two hunks: the first one is the real fix, the second unmaps dead exception handlers (that generally happen with nested `finally` clauses) which otherwise may trigger JRE verifier errors. That second hunk could be removed if the performance hit is considered undesirable.

Closes #915.

### CODE REVIEW

File: src/org/mozilla/classfile/ClassFileWriter.java [hunk 1]
```diff
@@ -1605,7 +1605,11 @@ private void killSuperBlock(SuperBlock sb) {
                     int handlerPC = getLabelPC(ete.itsHandlerLabel);
                     SuperBlock handlerSB = getSuperBlockFromOffset(handlerPC);
                     locals = handlerSB.getLocals();
-                    break;
+                    if (handlerSB.isInitialized()) {
+                        break;
+                    } else {
+                        continue;
```
Comment (tuchida) [inline src/org/mozilla/classfile/ClassFileWriter.java:1611]: Do you need to `continue`?
Since it is `if (sbStart > eteStart &&` and ` if (eteStart > sbStart &&`, the result is the same, but it feels more readable to write the same code as here.
https://github.com/mozilla/rhino/blob/f33a0c11f24f86fc6fff433f632a5013ca50e9af/src/org/mozilla/classfile/ClassFileWriter.java#L1617-L1620

**Review by tuchida — COMMENTED** [review]
Thank you very much for fixing it. Once this has been merged, #916 will be ready for review.

File: src/org/mozilla/classfile/ClassFileWriter.java (hunk 1 above)
Comment (carlosame) [reply src/org/mozilla/classfile/ClassFileWriter.java:1611]: Thank you for your review. I try to be efficient in a hot code path (the comment immediately above says so, and I agree), and while perhaps a smart JIT compiler would put a jump right there, I'd rather put it myself and make no assumptions about the JIT. :-)

**Comment by gbrail** [comment]
This is great -- thanks for tracking it down and fixing it!
