### PR TITLE
Fix: methods cannot be used as constructor

### LINKED ISSUE #1299: Support ES2015 Method Definitions - prevent methods as constructor
See:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions
- https://stackoverflow.com/a/50971728/7049810

While Rhino supports the method shorthadn (`var x = {foo(){}}`), it doesn't:
- ~~support `super`~~
- prevent calling the method as a constructor (new x.foo())
- ~~support generator methods~~

### PR DESCRIPTION
**Pull request by andreabergia**
The spec says that invoking a method as a constructor is not valid, but invoking normal functions is. This is, for example, `node`:

```js
> o = { method() {}, notAMethod: function() {} }
{ method: [Function: method], notAMethod: [Function: notAMethod] }
> new o.method()
Uncaught TypeError: o.method is not a constructor
> new o.notAMethod()
notAMethod {}
```

This PR implements the same behavior in Rhino, and fixes #1299.

### CODE REVIEW

**Comment by gbrail** [comment]
This makes sense to me, but I wonder how much existing code it could break and whether we should put it behind a "VERSION_ES6" or a "VERSION_ECMASCRIPT" flag just in case -- then again, since it didn't break any of MozillaSuiteTest perhaps it's not a big problem.

**Review by gbrail — COMMENTED** [review]
I'm willing to be convinced on this, but I think that since this breaks things that may have worked before, we should check that language version is >= VERSION_ES6 before throwing this exception. I'm not sure that we will put this in 1.8.0, but can merge it soon after.

**Comment by andreabergia** [comment]
> I'm willing to be convinced on this, but I think that since this breaks things that may have worked before, we should check that language version is >= VERSION_ES6 before throwing this exception.

Added a check on the language version.

File: rhino/src/main/java/org/mozilla/javascript/BaseFunction.java [hunk 1]
```diff
@@ -408,6 +408,11 @@ public Object call(Context cx, Scriptable scope, Scriptable thisObj, Object[] ar
 
     @Override
     public Scriptable construct(Context cx, Scriptable scope, Object[] args) {
+        if (cx.getLanguageVersion() >= Context.VERSION_ES6 && this.getHomeObject() != null) {
```
Comment (rbri) [inline rhino/src/main/java/org/mozilla/javascript/BaseFunction.java:411]: usually we do not use this (only in setters when it is required)

**Review by rbri — APPROVED** [review]
LGTM

**Comment by gbrail** [comment]
Looks good to me -- I agree about the excessive use of "this" but I'd rather move forward ;-) Thanks!
