### PR TITLE
Fix stack generation in interpreted mode

### LINKED ISSUE #2044: Error stack lost
```
try {
    null.toString();
} cath (e) {
    console(e + e.stack);
}
```
TypeError: Cannot call method “toString” of null	at <Unknown source>:4

### PR DESCRIPTION
**Pull request by rPraml**
This fixes #2044

### CODE REVIEW

File: testutils/src/main/java/org/mozilla/javascript/testutils/Utils.java [hunk 1]
```diff
@@ -240,7 +240,7 @@ public static void assertWithAllModes(
                         cx.setLanguageVersion(languageVersion);
                     }
                     final Scriptable scope = cx.initStandardObjects();
-                    final Object res = cx.evaluateString(scope, script, "test.js", 0, null);
+                    final Object res = cx.evaluateString(scope, script, "test.js", 1, null);
```
Comment (rPraml) [inline testutils/src/main/java/org/mozilla/javascript/testutils/Utils.java:243]: @rbri would you agree to change this value to `1`

File: rhino/src/test/java/org/mozilla/javascript/tests/ErrorHandlingTest.java [hunk 2]
```diff
@@ -37,23 +38,52 @@ public static void generateJavaError() {
     @Test
     public void throwError() {
         testIt(
-                "throw new Error('foo')",
+                "\n" // 1
+                        + "throw new Error('foo')", // 2
```
Comment (rPraml) [inline rhino/src/test/java/org/mozilla/javascript/tests/ErrorHandlingTest.java:42]: added some linebreaks here (comments are for Spotless)

File: rhino/src/main/java/org/mozilla/javascript/ScriptRuntime.java [hunk 3]
```diff
@@ -5082,6 +5082,9 @@ public static Scriptable newCatchScope(
             // set exception in Error objects to enable non-ECMA "stack" property
             if (errorObject instanceof NativeError) {
                 ((NativeError) errorObject).setStackProvider(re);
+                if (cx.isInterpretedMode()) {
+                    ((NativeError) errorObject).getStackDelegated();
```
Comment (rPraml) [inline rhino/src/main/java/org/mozilla/javascript/ScriptRuntime.java]: In interpreted mode, we must "capture" the stack on creation. (although it is not needed)

The computation is done [here](https://github.com/mozilla/rhino/pull/1956/files#diff-064c6e0ae69de426d768d3c598d6975a85b9acf9defa0a605d6a21612d387e8bR1154)

@aardvark179 - maybe you can take a look at this, if this solution is OK

**Comment by rPraml** [comment]
I think, this was really a regression of #1956

Formerly, the line info was stored in the exception
https://github.com/mozilla/rhino/pull/1956/files#diff-064c6e0ae69de426d768d3c598d6975a85b9acf9defa0a605d6a21612d387e8bL1009

I have re-used the `int[]` but changed it `int` which is technically an API change, if someone has inherited from RhinoException

File: testutils/src/main/java/org/mozilla/javascript/testutils/Utils.java (hunk 1 above)
Comment (rbri) [reply testutils/src/main/java/org/mozilla/javascript/testutils/Utils.java:243]: Yes fine for me

**Comment by rbri** [comment]
@gbrail / @andreabergia i like to merge this - any objections?

**Comment by andreabergia** [comment]
> @gbrail / @andreabergia i like to merge this - any objections?

Fine with me. I agree with Duncan that the minor change to the API is ok for me: it's not public stuff anyway.

**Comment by rbri** [comment]
Thanks a lot
